export const ADD_USER = 'ADD_USER';
export const ADD_USERS = 'ADD_USERS';
export const USERS_FAILED = 'USERS_FAILED';
export const USERS_LOADING = 'USERS_LOADING';

export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_LOADING = 'USER_LOGIN_LOADING';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';

export const MESSAGES_LOADING = 'MESSAGES_LOADING';
export const MESSAGES_FAILED = 'MESSAGES_FAILED';
export const ADD_MESSAGES = 'ADD_MESSAGES';
export const ADD_MESSAGE = 'ADD_MESSAGE';
