export const ADD_USER = 'ADD_USER';
export const ADD_USERS = 'ADD_USERS';
export const USERS_FAILED = 'USERS_FAILED';
export const USERS_LOADING = 'USERS_LOADING';

export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_LOADING = 'USER_LOGIN_LOADING';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';

export const SPECIFIC_MESSAGE_LOADING = 'SPECIFIC_MESSAGE_LOADING'
export const SPECIFIC_MESSAGE_FAILED = 'SPECIFIC_MESSAGE_FAILED'
export const ADD_SPECIFIC_MESSAGES = 'ADD_SPECIFIC_MESSAGES'
export const ADD_SPECIFIC_MESSAGE = 'ADD_SPECIFIC_MESSAGE'

export const CHATCONTACTS_LOADING = 'CHATCONTACTS_LOADING'
export const CHATCONTACTS_FAILED = 'CHATCONTACTS_FAILED'
export const CHATCONTACTS = 'CHATCONTACTS'

export const NOTETOSELF_LOADING = 'NOTETOSELF_LOADING'
export const NOTETOSELF_FAILED = 'NOTETOSELF_FAILED'
export const NOTETOSELF = 'NOTETOSELF'

